version: '3.8'
services:
  web:
    image: nginx:1.19.2
    container_name: web
    volumes:
    - ${PWD}/site-content:/usr/share/nginx/html
    - ${PWD}/conf/default.conf:/etc/nginx/conf.d/default.conf
    - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
    - ${PWD}/log:/var/log/nginx
    - ${PWD}/certs:/etc/nginx/certs
    ports:
    - "8080:80"
    - "8443:443"
